language: python

matrix:
  include:
    - env: TOX_ENV=py310-djangomain
      python: 3.10
    - env: TOX_ENV=py39-djangomain
      python: 3.9
    - env: TOX_ENV=py38-djangomain
      python: 3.8
    - env: TOX_ENV=py310-django42
      python: 3.10
    - env: TOX_ENV=py39-django42
      python: 3.9
    - env: TOX_ENV=py38-django42
      python: 3.8
    - env: TOX_ENV=py310-django41
      python: 3.10
    - env: TOX_ENV=py39-django41
      python: 3.9
    - env: TOX_ENV=py38-django41
      python: 3.8
    - env: TOX_ENV=py310-django40
      python: 3.10
    - env: TOX_ENV=py39-django40
      python: 3.9
    - env: TOX_ENV=py38-django40
      python: 3.8
    - env: TOX_ENV=py39-django32
      python: 3.9
    - env: TOX_ENV=py38-django32
      python: 3.8
    - env: TOX_ENV=py37-django32
      python: 3.7
    - env: TOX_ENV=py36-django32
      python: 3.6
    - env: TOX_ENV=py39-django31
      python: 3.9
    - env: TOX_ENV=py38-django31
      python: 3.8
    - env: TOX_ENV=py37-django31
      python: 3.7
    - env: TOX_ENV=py36-django31
      python: 3.6
    - env: TOX_ENV=py39-django30
      python: 3.9
    - env: TOX_ENV=py38-django30
      python: 3.8
    - env: TOX_ENV=py37-django30
      python: 3.7
    - env: TOX_ENV=py36-django30
      python: 3.6
    - env: TOX_ENV=py39-django22
      python: 3.9
    - env: TOX_ENV=py38-django22
      python: 3.8
    - env: TOX_ENV=py37-django22
      python: 3.7
    - env: TOX_ENV=py36-django22
      python: 3.6
    - env: TOX_ENV=flake8
    - env: TOX_ENV=docs

  allow_failures:
    - env: TOX_ENV=py310-djangomain
      python: 3.10
    - env: TOX_ENV=py39-djangomain
      python: 3.9
    - env: TOX_ENV=py38-djangomain
      python: 3.8

install: pip install tox

script: tox -e $TOX_ENV
